'\" t
.\"     Title: nm-initrd-generator
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/12/2020
.\"    Manual: System Administration
.\"    Source: NetworkManager 1.22.10
.\"  Language: English
.\"
.TH "NM\-INITRD\-GENERATOR" "8" "" "NetworkManager 1\&.22\&.10" "System Administration"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nm-initrd-generator \- early boot NetworkManager configuration generator
.SH "SYNOPSIS"
.HP \w'\fBnm\-initrd\-generator\fR\ 'u
\fBnm\-initrd\-generator\fR [\fIOPTIONS\fR...] \-\- [\fICMDLINE\fR...]
.SH "DESCRIPTION"
.PP
\fBnm\-initrd\-generator\fR
scans the command line for options relevant to network configuration and creates configuration files for an early instance of NetworkManager run from the initial ramdisk during early boot\&.
.SH "OPTIONS"
.PP
\fB\-c\fR | \fB\-\-connections\-dir\fR \fIpath\fR
.RS 4
Output connection directory\&.
.RE
.PP
\fB\-d\fR | \fB\-\-sysfs\-dir\fR \fIpath\fR
.RS 4
The sysfs mount point\&.
.RE
.PP
\fB\-s\fR | \fB\-\-stdout\fR
.RS 4
Dump connections to standard output\&. Useful for debugging\&.
.RE
.PP
\fICMDLINE\fR
.RS 4
The options that appear on the kernel command line\&. The following options are recognized:
.RS 4
\fBip\fR
.RE
.RS 4
\fBrd\&.route\fR
.RE
.RS 4
\fBbridge\fR
.RE
.RS 4
\fBbond\fR
.RE
.RS 4
\fBteam\fR
.RE
.RS 4
\fBvlan\fR
.RE
.RS 4
\fBbootdev\fR
.RE
.RS 4
\fBnameserver\fR
.RE
.RS 4
\fBrd\&.peerdns\fR
.RE
.RS 4
\fBrd\&.bootif\fR
.RE
.RS 4
\fBBOOTIF\fR
.RE
Please consult the
\fBdracut.cmdline\fR(7)
manual for the documentation of the precise format of the values supported\&.
.RE
.SH "EXIT STATUS"
.PP
\fBnm\-initrd\-generator\fR
exits with status 0\&. It ignores unrecognized options and prints an error message if it encounters a malformed option\&.
.SH "SEE ALSO"
.PP
\fBdracut.cmdline\fR(7),
\fBNetworkManager\fR(8)\&.
